name = "YAMLconfigs"
uuid = "d0519544-32dd-4a17-9a56-8c5ae55d459d"
authors = ["Jeffrey Sarnoff <jeffrey.sarnoff@ieee.org>" ]
version = "0.1.0"

[deps]
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia = "1.12"
YAML = "0.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
