Metadata:
  conformance: "IEEE SA P3109"
  version: "3.2.0"
  provider: "Provider"
  contact:
    email: 'info@implementer.site'
    uri: >
      https://implementer.site
  implementation:
    name: "release name"
    version: '1.0.0'
    date: 2026-01-11
  Configurations:
    uri: >
      https://implementer.site/P3109/Implementation/v1.0.0/Configurations.yaml
  Profiles:
    uri: >
      https://implementer.site/P3109/Implementation/v1.0.0/Profiles.yaml
  Constraints:
    uri: >
      https://implementer.site/P3109/Implementation/v1.0.0/Constraints.yaml
  Kappas:
    uri: >
      https://implementer.site/P3109/Implementation/v1.0.0/Kappas.yaml


Core32:
  - CoreOperations:
      - IEEE754_format: ["binary32"]
      - StochasticRounding:
        - StochasticB:
            - bits: "(Minimum(Precision, 16))"
  - BlockSizes (B):
      - core:
          - elements: 32
      - accelerated:
          - elements: 64
      - supported:
          - elements: "(2^i for i=2..22)"

Core64:
  - CoreOperations:
      - IEEE754_format: ["binary32", "binary64"]
    BlockSizes (B):
      - core:
          - elements: [16, 32]
      - accelerated:
          - elements: [64]
      - supported:
          - elements: "(2^i for i=4..24, [24, 48])"
  - Projections:
      - RoundingModes:
          - deterministic:
              - NearestTiesToEven
              - TowardNegative
              - TowardPositive
          - stochastic:
             - StochasticB:
                - bits: "(Minimum(Precision, 16))"  #needs same input and output
             - notes:
                - description: "xoroshiro128++ using top 16 bits."
                - reference_implementation:
                    https://implementer.site/P3109/Implementation/v1.0.0/Stochastic/Xoshiro128plusplus.c
      - SaturationModes:
          - OvfInf
          - SatPropagate
  - KappaApproximate:
    - SqrtFast
    - SinFast
    - ExpFast
