[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
YAMLconfigs = "d0519544-32dd-4a17-9a56-8c5ae55d459d"
PythonCall =  "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
PythonCall = "0.9 - 0.15"
julia = "1.12"
